

CREATE TABLE MARKETITEM (
		ID INTEGER NOT NULL,
		RECORDDATE VARCHAR(100) NOT NULL,
		ITEMID VARCHAR(100) NOT NULL,
		ITEMNAME VARCHAR(100) NOT NULL,
		ITEMDEVELOPER VARCHAR(100) NOT NULL,
		ITEMDEVELOPERRATING VARCHAR(100) NOT NULL,
		ITEMAVGRATING VARCHAR(50) NOT NULL,
		RATINGCOUNT VARCHAR(50) NOT NULL,
		LASTUPDATE VARCHAR(50) NOT NULL,
		NUMOFINSTALLS VARCHAR(50) NOT NULL,
		ITEMPRICE VARCHAR(50) NOT NULL,
		ITEMSIZE VARCHAR(50) NOT NULL,
		CONTENTRATING VARCHAR(50) NOT NULL,
		CURRENTVERSION VARCHAR(50) NOT NULL,
		FIVESTARS VARCHAR(50) NOT NULL,
		FOURSTARS VARCHAR(50) NOT NULL,
		THREESTARTS VARCHAR(50) NOT NULL,
		TWOSTARS VARCHAR(50) NOT NULL,
		ONESTAR VARCHAR(50) NOT NULL
	);



CREATE TABLE MARKETITEMREVIEWS (
		ID INTEGER NOT NULL,
		RECORDDATE VARCHAR(100) NOT NULL,
		REVIEWITEMID INTEGER NOT NULL,
		REVIEWUSER VARCHAR(100) NOT NULL,
		REVIEWDATE VARCHAR(100) NOT NULL,
		REVIEWPHONE VARCHAR(100) NOT NULL,
		REVIEWSTARVALUE VARCHAR(100) NOT NULL,
		REVIEWHEADING VARCHAR(100) NOT NULL,
		REVIEWBODY VARCHAR(3000) NOT NULL
	);

CREATE TABLE RATING_SUMMARY (
		RID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 41),
		SERVICEID INTEGER,
		QOSID INTEGER,
		SUMMARYKEY VARCHAR(128),
		SUMMARYVALUE VARCHAR(128)
	);
	
CREATE TABLE TEMPBDUMARKETITEMREVIEWS (
		ID INTEGER NOT NULL,
		RECORDDATE VARCHAR(100) NOT NULL,
		REVIEWITEMID VARCHAR(100) NOT NULL,
		REVIEWITEMB VARCHAR(100) NOT NULL,
		REVIEWITEMD VARCHAR(100) NOT NULL,
		REVIEWITEMU VARCHAR(100) NOT NULL,
		REVIEWITEMBDU VARCHAR(100) NOT NULL,
		REVIEWUSER VARCHAR(100) NOT NULL,
		REVIEWDATE DATE NOT NULL,
		REVIEWPHONE VARCHAR(100) NOT NULL,
		REVIEWSTARVALUE VARCHAR(100) NOT NULL,
		REVIEWHEADING VARCHAR(100) NOT NULL,
		REVIEWBODY VARCHAR(3000) NOT NULL,
		REVIEWBWORDLIST VARCHAR(500) NOT NULL,
		REVIEWDWORDLIST VARCHAR(500) NOT NULL,
		REVIEWUWORDLIST VARCHAR(500) NOT NULL
	);

CREATE TABLE REFRESHEDMARKETITEM (
		ID INTEGER NOT NULL,
		RECORDDATE VARCHAR(100) NOT NULL,
		ITEMID VARCHAR(100) NOT NULL,
		ITEMNAME VARCHAR(100) NOT NULL,
		ITEMDEVELOPER VARCHAR(100) NOT NULL,
		ITEMDEVELOPERRATING VARCHAR(100) NOT NULL,
		ITEMAVGRATING VARCHAR(50) NOT NULL,
		RATINGCOUNT VARCHAR(50) NOT NULL,
		LASTUPDATE VARCHAR(50) NOT NULL,
		NUMOFINSTALLS VARCHAR(50) NOT NULL,
		ITEMPRICE VARCHAR(50) NOT NULL,
		ITEMSIZE VARCHAR(50) NOT NULL,
		CONTENTRATING VARCHAR(50) NOT NULL,
		CURRENTVERSION VARCHAR(50) NOT NULL,
		FIVESTARS VARCHAR(50) NOT NULL,
		FOURSTARS VARCHAR(50) NOT NULL,
		THREESTARTS VARCHAR(50) NOT NULL,
		TWOSTARS VARCHAR(50) NOT NULL,
		ONESTAR VARCHAR(50) NOT NULL,
		INTERNALB DOUBLE NOT NULL,
		INTERNALD DOUBLE NOT NULL,
		INTERNALU DOUBLE NOT NULL,
		INTERNALBDU VARCHAR(50) NOT NULL,
		EXTERNALB DOUBLE NOT NULL,
		EXTERNALD DOUBLE NOT NULL,
		EXTERNALU DOUBLE NOT NULL,
		EXTERNALBDU VARCHAR(50) NOT NULL,
		TOTALB DOUBLE NOT NULL,
		TOTALD DOUBLE NOT NULL,
		TOTALU DOUBLE NOT NULL,
		TOTALBDU VARCHAR(50) NOT NULL
	);

CREATE TABLE UPDATELOG (
		ID INTEGER NOT NULL,
		MACHINE VARCHAR(40) NOT NULL,
		LOG VARCHAR(40) NOT NULL,
		UPDATETIME VARCHAR(40) NOT NULL
	);

CREATE TABLE TEMPPROGRESSIONBDUS (
		ID INTEGER NOT NULL,
		REVIEWITEMID VARCHAR(100) NOT NULL,
		REVIEWWEEK VARCHAR(100) NOT NULL,
		REVIEWITEMB VARCHAR(100) NOT NULL,
		REVIEWITEMD VARCHAR(100) NOT NULL,
		REVIEWITEMU VARCHAR(100) NOT NULL,
		REVIEWITEMBDU VARCHAR(100) NOT NULL
	);


CREATE TABLE SELECTEDTEMPMARKETITEM (
		ID INTEGER NOT NULL,
		RECORDDATE VARCHAR(100) NOT NULL,
		ITEMID VARCHAR(100) NOT NULL,
		ITEMNAME VARCHAR(100) NOT NULL,
		ITEMDEVELOPER VARCHAR(100) NOT NULL,
		ITEMDEVELOPERRATING VARCHAR(100) NOT NULL,
		ITEMAVGRATING VARCHAR(50) NOT NULL,
		RATINGCOUNT VARCHAR(50) NOT NULL,
		LASTUPDATE VARCHAR(50) NOT NULL,
		NUMOFINSTALLS VARCHAR(50) NOT NULL,
		ITEMPRICE VARCHAR(50) NOT NULL,
		ITEMSIZE VARCHAR(50) NOT NULL,
		CONTENTRATING VARCHAR(50) NOT NULL,
		CURRENTVERSION VARCHAR(50) NOT NULL,
		FIVESTARS VARCHAR(50) NOT NULL,
		FOURSTARS VARCHAR(50) NOT NULL,
		THREESTARTS VARCHAR(50) NOT NULL,
		TWOSTARS VARCHAR(50) NOT NULL,
		ONESTAR VARCHAR(50) NOT NULL,
		INTERNALB DOUBLE NOT NULL,
		INTERNALD DOUBLE NOT NULL,
		INTERNALU DOUBLE NOT NULL,
		INTERNALBDU VARCHAR(50) NOT NULL,
		EXTERNALB DOUBLE NOT NULL,
		EXTERNALD DOUBLE NOT NULL,
		EXTERNALU DOUBLE NOT NULL,
		EXTERNALBDU VARCHAR(50) NOT NULL,
		TOTALB DOUBLE NOT NULL,
		TOTALD DOUBLE NOT NULL,
		TOTALU DOUBLE NOT NULL,
		TOTALBDU VARCHAR(50) NOT NULL
	);

CREATE TABLE USER_RATINGS (
		RID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 17),
		SERVICEID INTEGER,
		RATING INTEGER,
		COUNT INTEGER DEFAULT 0,
		TOTAL INTEGER DEFAULT 0
	);




CREATE TABLE USERS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 2),
		USERNAME VARCHAR(40) NOT NULL,
		PASSWORD VARCHAR(20),
		ADMIN SMALLINT
	);
